action:
- any:
  - changed-files: ['action.yml', 'Dockerfile', 'entrypoint.sh']

tests:
- changed-files:
  - any-glob-to-any-file: testdata/**

automation:
- changed-files:
  - any-glob-to-any-file: .github/**

docs:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
