name: 'Run checkstyle with reviewdog'
description: '🐶 Run checkstyle with reviewdog on pull requests to improve code review experience.'
author: 'Dmitriy Belyaev'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'info'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for <linter-name> ###
  checkstyle_config:
    description: |
      Checkstyle configuration specifies which ruleset to apply during scan.
      There are two built-in configurations in checkstyle: [google_checks.xml,sun_checks.xml].
      google_checks.xml configures Checkstyle for the Google coding conventions (https://google.github.io/styleguide/javaguide.html)
      sun_checks.xml configures Checkstyle for the Sun coding conventions (https://www.oracle.com/java/technologies/javase/codeconventions-contents.html)
    required: true
    default: 'google_checks.xml'
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
