name: "Checkstyle for Java"
# description should be no more than 125 characters!
description: "🐶 Run checkstyle analysis on Java code and report results directly to pull request with the help of reviewdog."
author: "Dmitriy Belyaev"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
  workdir:
    description: "Working directory relative to the root directory."
    default: "."
  ### Flags for reviewdog ###
  level:
    description: "Report level for reviewdog [info, warning, error]"
    default: "info"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review]."
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
      Default is added.
    default: "added"
  fail_level:
    description: |
      Exits code 1 when errors are found at that level or above. Options are [none,any,error,warning,info]
      Default is `error`.
    default: "error"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    default: ""
  ### Flags for checkstyle ###
  checkstyle_config:
    description: |
      Checkstyle configuration specifies which ruleset to apply during scan.
      There are two built-in configurations in checkstyle: [google_checks.xml, sun_checks.xml].
      google_checks.xml configures Checkstyle for the Google coding conventions (https://google.github.io/styleguide/javaguide.html)
      sun_checks.xml configures Checkstyle for the Sun coding conventions (https://www.oracle.com/java/technologies/javase/codeconventions-contents.html)
    default: "google_checks.xml"
  checkstyle_version:
    description: |
      Checkstyle version to be used during analysis.
      For a list of available version numbers go to [Checkstyle release page](https://github.com/checkstyle/checkstyle/releases/).
      **IMPORTANT NOTE**
      This field will always try to follow Checkstyle releases as close as possible and will use the latest available by default.
      If it is not a default preference for your project, please, pin the needed version using this property.
    default: ""
  properties_file:
    description: |
      Location of the properties file relative to the root directory. This file serves as a means to resolve repetitive or predefined values within the checkstyle configuration file.
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "check"
  color: "green"
