name: Test - Reviewers

on:
  push:
    branches:
      - master
  pull_request:

# set empty default permissions and define them explicitly in each job for security
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-check:
    name: runner / checkstyle (github-check)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / checkstyle (github-pr-check)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/java/
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / checkstyle (github-pr-review)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir
