name: Test - Reviewers

on:
  push:
    branches:
      - master
  pull_request:

# set empty default permissions and define them explicitly in each job for security
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-check:
    name: runner / checkstyle (github-check)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / checkstyle (github-pr-check)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/java/
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / checkstyle (github-pr-review)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          exclude: |
            testdata/java/excluded
            testdata/java/excluded dir
